Feature/rank
HyunSangHan/meeting-frontend pull request #30
Opened 2019-08-13 07:03 UTC by tyj9327

Issue#29 에 작성한 부분에 대해 논의 필요

2019-08-13 08:20 UTC, HyunsangHan requested changes

2019-08-13 08:20 UTC, HyunsangHan commented on backend/meeting/views.py
> +        queryset = JoinedUser.objects.all()
get방식에서 이처럼 복수개의 joined_user를 가져올 일이 없을 것 같은데 @choiyeonseok 어떻게 생각하시나요?(오히려 기존처럼 joined_user 하나짜리가 더 필요하지 않을지)

그리고, 그런 걸 떠나서도 JoinedUser.objects.all()을 하면 이번 미팅이랑 상관없는 과거 미팅의 joined_user들까지 모두 뽑히게 되므로 코드 수정이 필요할 것 같습니다.

2019-08-13 08:20 UTC, HyunsangHan commented on backend/meeting/views.py
> +        user2delete = JoinedUser.objects.get(profile=my_profile, meeting=self.current_meeting)
기존에 있던 joined_user의 이름을 바꾼 이유가 있을까요?
user라는 게 이름에 들어가서, 추후 유지보수 시에 User모델과 혼동이 있을 수도 있을 것 같습니다.

그리고 filter를 get으로 바꾼 이유도 궁금합니다~

2019-08-13 08:20 UTC, HyunsangHan commented on backend/meeting/views.py
> +        after_joined_users = JoinedUser.objects.filter(rank__gte=user2delete.rank, meeting=self.current_meeting)
filter 조건에 성별도 들어가야하는 게 아닌가 싶네요.

2019-08-13 08:20 UTC, HyunSangHan commented on backend/meeting/views.py
> +        # cutline 산정 전 join 취소 - 취소자 바로 뒤의 joinedUser로부터 두 번 연속해서 같은 Rank를 가지고 있는 사람들 중 앞사람까지 rank를 하나씩 줄임
지금 여기는 delete메소드인데요. delete가 이루어진 이후부터 중복 rank의 케이스가 생기는 것이지, delete 순간에서는 중복 rank가 없지 않을까요? '두번 연속해서 같은 rank를 가지고 있는 사람들'이라고 고려한 이유가 궁금합니다~ 그냥 after_joined_users 모두 rank 1씩 줄여주면 되는 게 아닌가해서요.

2019-08-13 08:20 UTC, HyunSangHan commented on backend/meeting/views.py
> +                if prev_rank != after_joined_user.rank:
```python
if prev_rank != after_joined_user.rank
```
위 코드를 통해서 '정상적인 순위 나열'임을 판별하신 걸로 보이는데요. (즉, == 인 케이스는 비정상으로 간주)

그렇게 !=를 통해 판정하는 것보다는 

```python
if prev_rank < after_joined_user.rank
```
이게 더 의도하신 것에 부합하면서 로직적으로도 안전할 것 같네요. '두번 연속해서 같은 Rank를 가진다'에 대해서만 대비를 한 것은, 앞에서 1명만 탈퇴했다고 가정한 것인데요. 짧은 시간에 2명 이상 동시 탈퇴가 있을 수 있습니다.

앞에서 두명 이상이 동시 탈퇴하게 될 경우, 뒤에서 번호표를 뽑을 때 역전된 rank를 뽑을 수가 있으므로 등호보다는 부등호 조건이 나을 것 같습니다. 제 경험상 숫자로 줄세우는 로직의 상황에서는 대부분 등호조건이 위험했던 것 같습니다.

2019-08-13 08:20 UTC, HyunSangHan commented on backend/meeting/views.py
> +                if prev_rank != after_joined_user.rank:
근데 이걸 떠나서, 224번째줄 코멘트처럼, 이걸 판정하는 게 필요한지 잘 모르겠어서 필요성부터 살펴보고 유지가 필요한 로직이라면 위처럼 수정을 검토해보면 될 것 같습니다.

2019-08-13 08:20 UTC, HyunSangHan commented on backend/meeting/views.py
> +                #################
흠 일단 236번째줄처럼 하면 후순위 사람도 참여되는 거겠군요.
논의되면 짜는 걸로 합시다.

2019-08-13 08:20 UTC, HyunSangHan commented on backend/meeting/views.py
> +            user2delete.delete()
242번째줄에 있는 joined_uesr도 user2delete로 수정해야 로직이 맞을 것 같네요.

2019-08-13 08:20 UTC, HyunSangHan commented on backend/meeting/views.py
>      def delete(self, request, format=None):
profile API의 delete메소드의 경우에도 current_matching의 delete와 마찬가지 코멘트이므로, 여기는 생략하겠습니다.

2019-08-13 08:36 UTC, HyunSangHan commented
아 그리고 갑자기 문득 드는 생각이, join API의 delete메소드에서 저렇게 복잡하게 로직이 들어갈 게 아니라, 오히려 post메소드에서 들어가야 되는 거 아닌가요?

번호표 뽑을 때를 기준으로 그 번호표가 비정상이면 before_joined_user의 rank를 재배열한 뒤 자기 번호표를 다시뽑게끔 만들면 되지 않나 싶습니다.

2019-08-13 08:44 UTC, tyj9327 commented on backend/meeting/views.py
> +        user2delete = JoinedUser.objects.get(profile=my_profile, meeting=self.current_meeting)
지워져야 하는 유저라 생각해서 함수 내부에서 의미를 명확하게 하려 명칭을 바꾸어보았는데, 전체적으로 혼동이 온다면 수정하겠습니다!

2019-08-13 08:44 UTC, tyj9327 commented on backend/meeting/views.py
> +        after_joined_users = JoinedUser.objects.filter(rank__gte=user2delete.rank, meeting=self.current_meeting)
앗 그렇겠네요 수정하겠습니다

2019-08-13 08:51 UTC, tyj9327 commented
그렇게 한다면 만약 새로이 포스트할 일(새로운 조인)이 없는 경우 탈퇴한 사람 뒤로 조인한 다른 사람들의 랭크가 수정이 안될것 같습니다!

2019-08-13 08:52 UTC, tyj9327 commented on backend/meeting/views.py
> +        # cutline 산정 전 join 취소 - 취소자 바로 뒤의 joinedUser로부터 두 번 연속해서 같은 Rank를 가지고 있는 사람들 중 앞사람까지 rank를 하나씩 줄임
아, 생각해보니 그렇네요. 제가 딜리트가 되는 중에 새로운 사람이 동시에 조인할 수 있다고 착각하고 코드를 짠 것 같습니다. 그렇게 수정하는게 올바른 것 같네요!

2019-08-13 08:56 UTC, HyunSangHan commented
> 그렇게 한다면 만약 새로이 포스트할 일(새로운 조인)이 없는 경우 탈퇴한 사람 뒤로 조인한 다른 사람들의 랭크가 수정이 안될것 같습니다!

그렇긴 하네요~ 하지만, 그 케이스는 아래와 같이 보완 가능해보입니다.
- cutline이 아직 정해지지 않은 상황 : cutline을 meeting에 넣는 로직(즉 current_meeting의 patch메소드)에다가 rank 수정 로직을 추가
- cutline이 이미 정해진 상황 : 더이상 rank를 새로 뽑을 일이 없으므로 번호표가 비정상적이 될 상황이 없음

즉, join API의 post메소드와 current_meeting API의 patch메소드에만 rank 수정 로직을 넣어두면 되지 않을까 싶은데, 이렇게 하면 놓치는 case가 있을까요?

2019-08-13 09:06 UTC, tyj9327 commented on backend/meeting/views.py
> +        queryset = JoinedUser.objects.all()
아 잠시 런서버 하려고 수정해뒀던 코드입니다! 다시 수정하겠습니당

2019-08-13 09:11 UTC, tyj9327 commented on backend/meeting/views.py
> +        # cutline 산정 전 join 취소 - 취소자 바로 뒤의 joinedUser로부터 두 번 연속해서 같은 Rank를 가지고 있는 사람들 중 앞사람까지 rank를 하나씩 줄임
그런데 정말 말도 안되게 절묘한 타이밍으로 저 코드가 실행되는 찰나의 시간에 누군가 조인을 한다면... 저 코드가 필요하긴 할거같긴하네요..?

2019-08-13 09:17 UTC, tyj9327 commented
그렇다면 프론트에서 유저가 탈퇴했거나 조인을 취소한 경우에 한 번 더 api를 호출해야 하는 번거로움이 생기지는 않나요?

2019-08-13 09:44 UTC, HyunSangHan commented on backend/meeting/views.py
> +        queryset = JoinedUser.objects.all()
런서버할 때 통째로 주석처리 하는 게 더 편하고 이렇게 머지하게 될 때를 대비해서 더 안전할 듯합니다!

2019-08-13 09:52 UTC, HyunSangHan commented on backend/meeting/views.py
> +        # cutline 산정 전 join 취소 - 취소자 바로 뒤의 joinedUser로부터 두 번 연속해서 같은 Rank를 가지고 있는 사람들 중 앞사람까지 rank를 하나씩 줄임
실제로 인스턴스에 대한 delete()의 실행은 맨 마지막에 이루어지므로, 제 생각엔 그 우려되는 term이 거의 없다고 봐도 무방할 것 같습니다.

2019-08-13 09:54 UTC, HyunSangHan commented
> 그렇다면 프론트에서 유저가 탈퇴했거나 조인을 취소한 경우에 한 번 더 api를 호출해야 하는 번거로움이 생기지는 않나요?

아마 없을 듯합니다. 어차피 cutline넣어주는 함수가 실행되는 순간이 join을 마감한 시점이기 때문에 더이상 rank변동을 시켜줄 니즈가 없게 됩니다. 즉, cutline넣는 함수가 도는 시점이 이 rank재배열을 마지막으로 해주는 정리의 순간이라고 보면 될 것 같습니다.

2019-08-13 10:08 UTC, tyj9327 commented
아 생각해보니 그렇군요 엄밀한 rank가 필요하지가 않으니까요. 알겠습니다! 이 다음 커밋에서 반영하도록 하겠습니다.

2019-08-13 10:09 UTC, tyj9327 commented
앗, 그런데 그러면 그냥 딜리트에서 코드 네줄정도만 있으면 될 듯 한데, 그냥 두어도 괜찮지 않을지.. 만나서 이야기하도록 하겠습니다!

2019-08-13 16:01 UTC, HyunsangHan commented on backend/meeting/views.py
> +            if not match.joined_male.is_matched or not match.joined_female.is_matched:
```python
if match.is_greenlight_male and match.is_greenlight_female and (not match.joined_male.is_matched or not match.joined_female.is_matched):
```

문법이 맞는지 모르겠는데, else가 따로 없으므로 이렇게 하면 코드가 더 간결해질 것 같네요!

2019-08-13 16:01 UTC, HyunsangHan commented on backend/meeting/views.py
> +                kakao_chatting.save()
```python
match.save()
```
추가해야 채팅방url이 저장될 것 같네요.

2019-08-13 16:01 UTC, HyunsangHan commented on backend/meeting/views.py
>          queryset = Meeting.objects.filter(meeting_time__gte=timezone.now()).order_by('meeting_time').first()
요거는 어차피 serializer를 쓰는 것도 아니고, queryset 대신 current_meeting이라고 이름지으면 더욱 명확할 것 같아요~

2019-08-13 16:01 UTC, HyunSangHan commented on backend/meeting/views.py
> +        queryset = JoinedUser.objects.filter(meeting=self.current_meeting)
joined_user가 복수개가 아니라 1개만 뽑혀야 할 것 같습니다.(234번줄도 수정 필요)

2019-08-13 23:04 UTC, HyunSangHan commented on backend/meeting/views.py
> +                        Matching.objects.create(joined_male=joined_users_male[i], joined_female=joined_users_female[numbers[0]], trial_time=request.data["trial_time"])
이 runned == 9 를 넣은 게, 그 중복매칭이 어쩔 수 없이 이루어져야 하는 경우 때문인 거죠?

2019-08-15 05:13 UTC, tyj9327 commented on backend/meeting/views.py
> +                        Matching.objects.create(joined_male=joined_users_male[i], joined_female=joined_users_female[numbers[0]], trial_time=request.data["trial_time"])
맞습니다!

2019-08-15 05:40 UTC, tyj9327 commented on backend/meeting/views.py
>          queryset = Meeting.objects.filter(meeting_time__gte=timezone.now()).order_by('meeting_time').first()
반영했습니다.

2019-08-15 05:47 UTC, c-yeonwoo approved these changes

2019-08-15 07:32 UTC, HyunsangHan approved these changes

2019-08-15 07:44 UTC, merged