Backend/feature/matching
HyunSangHan/meeting-frontend pull request #4
Opened 2019-07-20 16:35 UTC by qwerty98765

* 매칭 API 초안 작성
-> JoinedUser에 성별을 추가해야 매칭을 이성끼리 할 수 있을 것 같아 추가
-> is_matched가 False인 경우 매칭 생성(셔플) - filter 잘 쓴 것인지 검증 필요
-> Matching instance를 매번 delete하거나 회차 반영은 아직 안 되었네요(지금 생각났네요ㅠ)
-> PATCH METHOD의 경우 그린라이트, 안주제공 등을 변경할 수 있게 작성
(MeetingAPI에 대해 PATCH 하나로 여러 가지를 변경할 수 있어야해서 매번 그 항목들을 지금은 다 받아야 하게 구현)

2019-07-20 22:13 UTC, HyunSangHan commented
일단 어젯밤 merge한 develop 브랜치와의 conflicts를 해결해야 할 것 같네요.

2019-07-20 23:21 UTC, HyunsangHan commented on backend/meeting/models.py
> +    is_female = models.BooleanField(default=False)
1. 만약 이 필드를 새로 추가한다면 Profile모델과 마찬가지로 is_male로 통일하면 좋을 것 같네요.
2. 사실 이 필드를 추가하지 않고도 JoinedUser필터링이 가능합니다. 따라서 이 필드를 굳이 추가하지 않아도 될 것 같습니다. 이에 대해서는 해당 코드 부분에 가서 더 구체적으로 comment하도록 하겠습니다.

2019-07-20 23:21 UTC, HyunsangHan commented on backend/meeting/views.py
> +        joined_users_female = list(JoinedUser.objects.filter(is_matched=False and is_female=True))
JoinedUser에 성별필드를 새로 추가하는 것도 괜찮지만, 아래와 같은 코드는 어떨까요? 그러면 새로 필드를 추가하지 않아도 됩니다.

joined_users_male = list(JoinedUser.objects.filter(is_matched=False, profile__is_male = True))
joined_users_female = list(JoinedUser.objects.filter(is_matched=False, profile__is_male = False))

2019-07-20 23:21 UTC, HyunsangHan commented on backend/meeting/views.py
> +            serializer = MatchingSerializer(Matching.objects.create(joined_male=joined_users_male[i], joined_female=joined_users_female[i]))
어찌보면 이 서비스에서 가장 핵심인 셔플 로직인데, 짜느라 고생많았겠네요!

나중에 좀더 로직을 고도화하기 위해서는, 1차셔플-2차셔플-3차셔플이 될 때 매칭되는 이성이 중복되지 않도록 막는 로직도 필요할 수 있겠습니다.(예컨대, 2차매칭 때 1차에서 매칭됐던 이성이 연속으로 매칭되지 않도록 하기 위함)
이에 대해서는 이따 회의시간에 시간이 가능하다면 더 논의해봅시다.

2019-07-20 23:21 UTC, HyunsangHan commented on backend/meeting/views.py
> +            # url을 할당하는 것도 괜찮을 것 같네요 (50개는 우리가 매주 admin으로 입력해놓고)
동의합니다.

2019-07-20 23:21 UTC, HyunsangHan commented on backend/meeting/views.py
> +        serializer.is_greenlight_male = request.data.is_greenlight_male
이 PATCH 메소드, 디버깅까지 완료된 코드일까요?
1. serializer.필드명 => 이거 유효한 문법인가요?
2. serializer의 필드를 건드리는 게 가능한가요? 참고로 제가 어제 실험해보았을 때에는 serializer는 수정이 안되는 것 같아서 딕셔너리 자료형을 이용해서 원하는 값을 넣어두고 나머지를 request.data가 덮어쓴 후 serialize하는 형태로 구현했었습니다.

2019-07-20 23:21 UTC, HyunSangHan commented on backend/meeting/views.py
> +        queryset = Matching.objects.filter(id=request.data.id)
request에서 정확하게 이 matching인스턴스의 id를 보내줄 수 있을까요?
그렇다면 이 코드처럼 한번에 원하는 matching쿼리셋에 접근할 수 있으므로 상관 없겠지만,

만일 그럴 수 없다면,
  1. 현재 시각을 활용해 current_meeting을 찾고,
  2. request를 통해 넘어온 사용자정보를 활용해 User=>Profile=>JoinedUser순으로 찾아내면, meeting_id와 joined_user_id를 활용해 Matching모델을 필터링할 수 있지 않을까 싶습니다.

그렇게 되면 여러 셔플을 거쳤을 경우 여러개의 matching인스턴스를 쿼리셋에 가지게 될 텐데요. 원하는 매칭만 쏙 뽑아내기 위해서,
  1. 클라이언트단 request에서 셔플회차를 보내주면 그걸 Matching모델의 trial_time필드를 이용해서 하나의 인스턴스만 뽑아내거나
  2. (엉뚱한 게 뽑히진 않을지 나중에 구현 후에 반드시 검증은 필요하겠지만) 단순히 .last()로 마지막 인스턴스를 뽑아내는 것도 가능할 수 있을 듯합니다.

2019-07-20 23:21 UTC, HyunSangHan commented on backend/meeting/views.py
> +            serializer.kakao_chattingroom = "kakao_chat_example/1"
현재는 serializer 안에 있는 각 데이터를 덮어씌우는 형태로 되어있는데요. PATCH의 취지(?)를 더 살리기 위해서는 31~37번줄 코드를 아래와 같이 수정 가능할 것 같습니다.
  ```python
  serializer = MatchingSerializer(queryset, data=request.data, partial=True)
  ```
이렇게 쓰게 되면 request에서 보내온 data가 예를 들어
  ```
{
    is_gift_male : true
}
  ```
이런식으로 다른 필드 언급 없이 단 한줄만 있어도, 이게 기존 값과 다를 경우 이것만 딱 업데이트를 해주게 됩니다.(기존에 is_gift_male은 당연히 false였을 테니, 위 예시에서는 업데이트가 되게 되겠죠?)
따라서 API개발 시 굳이 if문을 써주지 않아도 client단의 request에 따라 알아서 반응해주기 때문에 모든 case가 커버 가능합니다.

단, kakao_chattingroom은 조건에 따라 데이터를 채워넣어줘야하는데요. 이에 대해서는 어느 정도 적용 가능할 것 같은 구현 아이디어가 있는데, 이따 회의 때 공유할 테니 함께 논의해봐요~

2019-07-21 01:26 UTC, HyunSangHan commented on backend/meeting/views.py
> +class MatchingAPI(APIView):
views.py에 있는 class는 모두 API인데, 이름에 API라고 꼭 붙여줘야 할까요?
CurrentMatching이런 건 어떨까요?(그러면 url은 current_matching)
그러고 GET방식으로 현재 차수의 셔플된 매칭을 가져오게 하는 걸 추가해주면 더 REST스럽지 않을까 싶습니다.

2019-07-22 06:17 UTC, qwerty98765 commented on backend/meeting/views.py
> +class MatchingAPI(APIView):
좋은 생각이네요. 반영했습니다!

2019-07-22 06:25 UTC, qwerty98765 commented on backend/meeting/views.py
> +        serializer.is_greenlight_male = request.data.is_greenlight_male
덕분에 많이 배우네요!!

2019-07-22 06:29 UTC, qwerty98765 commented on backend/meeting/views.py
> +        queryset = Matching.objects.filter(id=request.data.id)
matching의 id를 보내주는 것은 일단은 가능할 것 같기는한데 이는 어떻게 짜느냐에 따라 다를 것 같네요. 지금은 아니지만 결국에는 아마 status 말고도 matching등의 정보를 front에 넘겨주게 될 것 같아서 일단은 놔두겠습니다! 좋은 지적이네요.

2019-07-22 06:30 UTC, qwerty98765 commented on backend/meeting/views.py
> +            serializer.kakao_chattingroom = "kakao_chat_example/1"
반영했습니다! 또 배워갑니다~~

2019-07-22 06:30 UTC, qwerty98765 commented on backend/meeting/views.py
> +            serializer = MatchingSerializer(Matching.objects.create(joined_male=joined_users_male[i], joined_female=joined_users_female[i]))
일단 회의 때 놔둔 로직 그대로 두겠습니다. 셔플을 어떻게 할지는 조금 더 얘기해봐요!

2019-07-22 11:16 UTC, qwerty98765 commented
> 일단 어젯밤 merge한 develop 브랜치와의 conflicts를 해결해야 할 것 같네요.

2019-07-22 11:49 UTC, tyj9327 approved these changes

2019-07-22 11:55 UTC, HyunsangHan approved these changes

2019-07-22 11:55 UTC, HyunSangHan commented on backend/meeting/views.py
> +        matched = list()
이거는 필요없어진 코드일까요?

2019-07-22 11:55 UTC, HyunSangHan commented on backend/meeting/views.py
> +            matched_matching = {
matched_matching 이름이 어려운 것 같기도 한데, successful_matching이라는 이름은 어떨까요?
(혹은, matched_data라든지..)

2019-07-22 11:57 UTC, HyunSangHan commented
나중에 ChatingRoom 모델 만드는 것 잊지 맙시다! 이슈에 등록해둘게요.

2019-07-22 12:15 UTC, HyunSangHan commented on backend/meeting/views.py
> +            }
그리고 나중에는, #6 이슈에 남긴 것처럼 ChattingRoom모델과 포린키로 연동해서, 여기서 dictionary형으로 직접 써주지 않고 chattingroom인스턴스를 하나 쏙 뽑아다가 시리얼라이저에 데이터를 넣어주는 게 어떨지 싶네요.

2019-07-22 12:23 UTC, HyunSangHan commented on backend/meeting/views.py
> +        return Response(serializer.data, statuso=status.HTTP_201_CREATED)
오타를 발견했습니다.

2019-07-22 12:31 UTC, HyunSangHan commented on backend/meeting/views.py
> +            if request.data.trial_time == 3:
elif로 써주는 게 좋지 않을까요? 각각의 조건문이 별개가 아니므로 그게 더 효율적일 것 같습니다.

2019-07-22 12:31 UTC, HyunSangHan commented on backend/meeting/views.py
> +                serializer = MatchingSerializer(Matching.objects.create(joined_male=joined_users_male[i], joined_female=joined_users_female[numbers[0]], trial_time=request.data.trial_time))
이쯤에서 양쪽(남녀) joined_user의 already_met_one(또는 two, three)필드를 채워줘야 하지 않을지 싶습니다.

2019-07-22 12:31 UTC, HyunSangHan commented on backend/meeting/views.py
> +class CurrentMatching(APIView):
GET방식도 만들어서, 현재 로그인되어있는 유저의 '현재 매칭' 인스턴스를 불러올 수 있게 해주면 언젠가 쓸 데가 있을 것 같아요!

2019-07-22 12:31 UTC, HyunSangHan commented on backend/meeting/views.py
> +            Matching.objects.filter(trail_time=request.data.trial_time, is_matched=False).delete()
trial_time 오타 수정이 필요해보입니다.

2019-07-23 14:55 UTC, HyunsangHan requested changes
중간중간에 오타가 있으니 태영님한테 넘겨주기 전에 전반적으로 한번 확인해주셔야 할 것 같습니다.

2019-07-24 07:48 UTC, qwerty98765 commented on backend/meeting/views.py
> +        matched = list()
어 이건 주석처리 해놨었는데 바꾸는 match들을 한번에 다 저장하는 과정으로 가려고 하다가 저번 회의 때 적은 것 같아요. 일단은 지워놓겠습니다.

2019-07-24 07:50 UTC, qwerty98765 commented on backend/meeting/views.py
> +            matched_matching = {
자주 쓰이는 변수가 아니라 최대한 자세히 successful_matching_data 로 바꾸었습니다!

2019-07-24 07:51 UTC, qwerty98765 commented
> 나중에 ChatitngRoom 모델 만드는 것 잊지 맙시다! 이슈에 등록해둘게요.

넵넵 좋아요!

2019-07-24 07:53 UTC, qwerty98765 commented on backend/meeting/views.py
> +        return Response(serializer.data, statuso=status.HTTP_201_CREATED)
엇 이거 고치고 올렸다고 생각한 부분인데 남아있었나보네요 바로 고쳤습니다!

2019-07-24 07:54 UTC, qwerty98765 commented on backend/meeting/views.py
> +            if request.data.trial_time == 3:
좋은 지적이네요!

2019-07-24 08:04 UTC, qwerty98765 commented on backend/meeting/views.py
> +                serializer = MatchingSerializer(Matching.objects.create(joined_male=joined_users_male[i], joined_female=joined_users_female[numbers[0]], trial_time=request.data.trial_time))
큰일날 뻔했네요. 근데 이 작업에는 굳이 request의 정보가 필요하거나 front로 나갈 정보가 없어서 그냥 instance에서 바로 save하도록 했습니다.

2019-07-24 08:09 UTC, qwerty98765 commented on backend/meeting/views.py
> +            Matching.objects.filter(trail_time=request.data.trial_time, is_matched=False).delete()
수정했습니다!

2019-07-24 09:10 UTC, HyunSangHan commented on backend/meeting/views.py
> +                while runned < 10:
3이 좀 적다고 생각했는데(runned가 1부터 시작이니 실제로는 2회라서..) 10 좋은 것 같네요.ㅎㅎ 어차피 10번 돌 확률이 높지 않아서 부하가 될 것 같지도 않고요.

2019-07-24 09:57 UTC, HyunSangHan commented on backend/meeting/views.py
> +        joined_user = JoinedUser.objects.filter(profile__user=request.data)
user정보가 request.data로 온다고 가정하고 이렇게 작성해주신 거죠?
@tyj9327 나중에 이어서 API 전반적으로 완성지을 때 디버깅이 필요할 텐데, 오류가 날 수 있으니 디버깅용으로 코드 수정해서 개발하는 것을 감안해두어야 할 것 같습니다.

2019-07-24 09:57 UTC, HyunSangHan commented on backend/meeting/views.py
> +            return Response(current_matching, status=status.HTTP_200_OK)
JoinedUser는 여러개의 Matching을 가질 수 있는 걸로 기억합니다.
따라서 joined_user.matching을 current_matching으로 두어 response하면 안되고, .filter()를 써서 joined_user와 meeting필드를 통해 일단 n개의 matching을 가져온 후, .last()로 가장 최신의 matching 인스턴스를 골라내서 response에 담아줘야 할 것 같네요.

2019-07-24 13:30 UTC, HyunsangHan approved these changes

2019-07-24 13:44 UTC, qwerty98765 commented on backend/meeting/views.py
> +            return Response(current_matching, status=status.HTTP_200_OK)
아 matching instance는 성사되지 않은 matching이라고 지우지 않고 남기는 거였나요? 다 지운다고 가정하고 짜서 이렇게 된 것 같아요. Joined user 말고 Matching도 history를 남길 것이라면 delete도 조금 바꿔야할 것 같긴하네요

2019-07-24 13:45 UTC, qwerty98765 commented on backend/meeting/views.py
> +                while runned < 10:
넵 안 그래도 10회로 바꾸었습니다!!

2019-07-24 13:46 UTC, qwerty98765 commented on backend/meeting/views.py
> +        joined_user = JoinedUser.objects.filter(profile__user=request.data)
각자 request에 어떤 데이터가 들어온 것을 가정으로 했는지 정리해두는 것도 괜찮을 것 같네요.

2019-07-24 13:55 UTC, HyunSangHan commented on backend/meeting/views.py
> +            return Response(current_matching, status=status.HTTP_200_OK)
아, 매칭인스턴스를 그때그때 지우는 거였군요! 전 그냥 한 meeting이 다 끝나고나면 한번에 지운다고 생각했어요. 그때그때 지우는 거라면, 여기서 뽑히는 건 n개가 아니라 1개의 인스턴스겠네요.
하지만 filter로 뽑았을 때, 아마도 쿼리셋으로 뽑힐 거에요. 따라서 n개의 matching을 가져온 것과 마찬가지로, 어쨌든 .last()든 .first()든 이용해서 하나만 콕 찝어내야 하는 걸로 알고 있습니다.(filter가 아닌 get의 개념을 구현하기 위해)

2019-07-24 13:56 UTC, HyunSangHan commented on backend/meeting/views.py
>          return Response(status=status.HTTP_202_ACCEPTED)
불발된 matching인스턴스를 그때그때 지우는 게 여기인가요?
그럼 다음 셔플이 돌아가는 시점 직전에 맞춰서 이 API를 호출하면 되는 거죠?

2019-07-24 16:01 UTC, tyj9327 commented on backend/meeting/views.py
> +        joined_user = JoinedUser.objects.filter(profile__user=request.data)
정리해놔야겠네요 아무래도! 알겠습니다

2019-07-25 14:22 UTC, HyunSangHan commented on backend/meeting/views.py
> +            return Response(current_matching, status=status.HTTP_200_OK)
@qwerty98765 일단 merge하겠습니다. @tyj9327 마무리 작업하다가 만약에 에러가 나게 된다면 .last()를 붙여주세요~

2019-07-25 14:23 UTC, merged

2019-07-27 04:49 UTC, qwerty98765 commented on backend/meeting/views.py
>          return Response(status=status.HTTP_202_ACCEPTED)
네네 그렇게 하면 될 것 같아요!

2019-07-27 04:50 UTC, qwerty98765 commented on backend/meeting/views.py
> +            return Response(current_matching, status=status.HTTP_200_OK)
아아 그렇군요! 일단 merge가 이미 되었으니 그렇게 하는걸로 할게요 ㅠ