Feature/player
HyunSangHan/meeting-frontend pull request #58
Opened 2019-08-30 05:58 UTC by choiyeonseok

1. main의 image wrapper 수정했습니다.
2. 지난 코멘트에서 수정못한 변수명 수정도 반영했습니다.

2019-08-31 12:43 UTC, HyunsangHan requested changes

2019-08-31 12:43 UTC, HyunSangHan commented on frontend/src/components/details/CounterPlayer.js
> +                            <div className="images">
Profile.js의 이미지 스와이프(가로스크롤) 기능과 아직 꽤 차이가 있는 것 같습니다. 이미 구현해 둔 프로필수정화면의 코드를 좀더 자세히 살펴보시고 코드 수정이 필요할 듯합니다. 우선 프로필수정화면의 너비를 조금씩 늘렸다 줄였다 조정하면서 어떤식으로 css 적용을 해두었는지 디테일들을 봐보시면 좋을 것 같습니다. width가 몇 픽셀일 때 이미지박스의 크기가 달라지는지, 언제부터 스크롤이 없어지면서 박스가 고정되는지, 그리고 어느 층위의 div에 이미지박스가 존재하는지 등을 뜯어보시면 아마 금방 구조 이해가 되실 것 같습니다.

일단, 프로필수정화면과의 UI상의 가장 큰 차이점은 아래와 같습니다.

![tm](https://user-images.githubusercontent.com/44132406/64063930-33bf8300-cc36-11e9-822e-5ab781cb897c.png)

이번에 코드 수정을 해주셔서 3번 영역만큼의 갭은 없애셨지만, 여전히 1,2,4영역 만큼의 갭이 남고 있습니다.
width가 작았을 때에는 4의 갭이 없어보이는 것처럼 보이는데요. width를 좀 늘려보면 이 갭이 없어지지 않았다는 것을 알 수 있습니다.
1,2의 갭은 아예 없어지지 않고 남아있는 걸로 보이고요.

반면에, 프로필수정화면을 보시면, 이미지박스와 화면 테두리까지의 갭이 아예 없습니다. 즉, 이미지를 감싼 부모 wrapper의 width가 100%라는 뜻입니다.
그런데 지금 작성해두신 코드를 보면, counter-container라는 css가 width:90%입니다.
따라서 counter-container의 속성을 가진 div의 자식div는 절대 너비 100%가 될 수 없고, 따라서 images-wrapper와 images가 counter-container의 자식 div인 이상 Profile.js처럼 전체에 가득차는(=width:100%의) 스와이프(가로스크롤)를 구현할 수 없게 됩니다. 

프로필수정화면은 아래와 같이, 스와이프 시에 화면너비의 100%를 활용하게 되어있음을 참고해보세요.

![tmx](https://user-images.githubusercontent.com/44132406/64064060-f1974100-cc37-11e9-8b2f-2eec2cdf38e1.png)

2019-09-03 06:13 UTC, HyunsangHan requested changes
count down 관련해서도 develop branch에 새로 merge되었으니, 수정하시고 push하시기 전에 develop branch와의 conflict도 해결해주세요~

2019-09-03 13:58 UTC, choiyeonseok commented on frontend/src/components/details/CounterPlayer.js
> +                            <div className="images">
4번의 갭이 있는줄은 몰랐네요,, 정확하게 조치하지 못한점 죄송합니다.
그런데 프로필과는 좀 다른점이 회색배경안에 흰색 박스가 하나더있기 때문에, 1,2번의 갭을 당연히 살려야한다고 생각했는데, 갭을 완전히 없애서 프로필처럼 해야된다는게 좀 이해가 안가군요, (현재 total-container div안에 counter-container와 images-wrapper가 병렬적으로 속해있습니다.) 

혹시 흰색박스가 사진위에서 끝나고 사진은 그냥 회색바탕에다만 하는건가요? 
그게아니라면 이번 코멘트로 제가 이해한 사항은,  화면을 줄였을때 이미지들이 흰색 박스를 무시하고 양쪽 가로로 꽉찬 모양을 보여야한다는것인지요?
![image](https://user-images.githubusercontent.com/42382027/64179586-623f9700-ce9e-11e9-9d71-8b64f9262dae.png)

2019-09-03 14:09 UTC, HyunSangHan commented on frontend/src/components/details/CounterPlayer.js
> +                            <div className="images">
네, 파란색테두리로 그려주신 개념이 맞는 걸로 보입니다.

zeplin보시면 아래와 같이 되어있는데, 이거를 예시로 보시면 될 듯 하네요. (초상권 차원에서 사진에 계신 분들 얼굴을 가렸습니다.)

왼쪽 예시는 스와이프를 오른쪽=>왼쪽으로 끝까지 넘겼을 때의 모습이고,
오른쪽 예시는 스와이프를 왼쪽=>오른쪽으로 끝까지 넘겼을 때의 모습입니다.
흰색박스가 있다고 해도 Profile.js와 구조적으로 다르지 않을 것 같습니다.

![image](https://user-images.githubusercontent.com/44132406/64180432-b72fdd00-ce9f-11e9-8a39-5a8b7a2de512.png)

2019-09-04 07:29 UTC, choiyeonseok commented
main.js의 image-wrapper수정하였는데, conflict해결하려고 develop풀받으니까 이전에 작업했던게 다 날라가서 팝업 버그 다시 해결해야할것같습니다.( 현재 매칭조회가 안되는데 해결방법이 있다면 알려주시면 감사드리겠습니다.)

2019-09-05 14:06 UTC, HyunSangHan commented
> main.js의 image-wrapper수정하였고, 푸시하려고 conflict해결하려고 develop풀받으니까 예전에 gift popup 작업했던게 다 날라가서 팝업 버그 다시 해결해야할것같습니다.( 현재 매칭조회가 안되는데 해결방법이 있다면 알려주시면 감사드리겠습니다.)

날아간 것은 github에 남아있는 commit을 뒤져서 해결해야 겠군요ㅠ 매칭조회 저는 되는데.. admin은 문제 없었나요?

2019-09-05 14:24 UTC, HyunsangHan requested changes

2019-09-05 14:24 UTC, HyunSangHan commented on frontend/src/components/details/CounterPlayer.js
> +                    <div className="images">
![image](https://user-images.githubusercontent.com/44132406/64349478-03128b80-d032-11e9-8174-749363dbba0c.png)

결과물을 보니 아직 전에 말씀드렸던 부분(당시 기준 1,2,4구간)은 그대로인 것 같네요. 기존과 같이 이 구간들을 이미지가 넘어가지 못하고 가려지고 있습니다. 게다가 이번 코드 push로 인해 새로운 문제점이 발견되었는데요. 아래와 같이, 좁은화면에서 왼쪽->오른쪽으로 스와이프한 경우 의미없는 여백이 생겨버리고 있습니다.

![image](https://user-images.githubusercontent.com/44132406/64349912-bd09f780-d032-11e9-9517-cfd884fedabb.png)

좀더 수정이 필요할 듯 보이네요^^;
가장 근본적인 문제는 images-wrapper의 width값이 90%라는 것입니다. 이게 90%면 절대로 너비 전체를 활용한 스와이프를 구현할 수 없습니다.

아래 캡처화면을 보시면 알 수 있을 듯합니다. 크롬 개발자도구를 통해 해당 element가 넘어갈 수 있는 최대 width를 살펴본 것입니다.

### CounterPlayer.js  
파란색으로 표시된 부분을 봐도 그렇고, css속성을 봐도 그렇고 너비가 100%에 못미치는 것을 알 수 있습니다.
![image](https://user-images.githubusercontent.com/44132406/64350343-7668cd00-d033-11e9-94a3-2549286e7026.png)

### Profile.js(참고용)
파란색으로 표시된 부분이 화면 너비를 가득 채우는 것을 볼 수 있습니다.(그렇기 때문에 가로 스크롤이 너비 전체에 적용될 '가능성'이 생기는 것입니다.) css속성을 읽어봐도 너비가 100%임을 알 수 있습니다.
![image](https://user-images.githubusercontent.com/44132406/64350394-8a143380-d033-11e9-8491-66cc7d66629f.png)

반응형 개발을 할 때에는 크롬을 통해 브라우저의 width값을 계속 줄였다 넓혔다 하면서 가로스크롤을 움직이는 실험을 해보는 게 필요하고, 뜻대로 작동하지 않을 때에는 저렇게 element를 inspect해서 어떤 구조가 잘못되었고 어떤 속성이 잘못들어갔는지를 debug하는 게 중요한데 크롬 개발자도구가 매우 효과적이니 이번 수정 때에는 한번 활용해보시길 권장합니다.  
  
해보시면서 잘 안되는 부분이 있다면 slack으로 언제든지 문의해주세요.

2019-09-05 15:00 UTC, HyunsangHan requested changes

2019-09-05 15:00 UTC, HyunsangHan commented on frontend/src/css/Main.scss
> +        width: 90%;
여기서 일단 잘못된 것 같네요...!
images-wrapper가 구조적으로 이 이미지들 영역의 가장 조상이 되는 부분인데 이걸 100%에서 90%로 수정하면 원하는 결과를 얻을 수 없게 됩니다. 혹시 왼쪽 회색배경만큼의 갭(즉, 흰색배경왼쪽테두리와 왼쪽브라우저 끝까지 사이의 갭)을 띄우기 위해서 이 %를 줄인 것인가요?
그렇게 하면 안되고, images-wrapper는 100%로 둔 다음에, 내부에 있는 images를 통해 실질적 너비를 컨트롤해야합니다. 물론 images는 images-wrapper안에서 가운데정렬로 구현한다는 가정 하에요.
그러고나서 흰색 배경내에서 이미지와 살짝 떨어지게 만드는 margin은 말그대로 margin을 이용해서 살짝만 떨어뜨려주면 되는 원리입니다~

2019-09-06 09:57 UTC, choiyeonseok commented on frontend/src/components/details/CounterPlayer.js
> +                    <div className="images">
오잉 제꺼에서는 저렇게까지는 안보였었는데 이상하군요,, 다시 봐보겠습니다.!

2019-09-07 03:02 UTC, choiyeonseok commented on frontend/src/css/Main.scss
> +        width: 90%;
근데 profile코드 그대로 가져와서 복붙했기때문에 90%된거 진작 수정했는데 왜 안올라갔는지 모르겠네요ㅜ

2019-09-07 06:13 UTC, HyunsangHan requested changes

2019-09-07 06:13 UTC, HyunSangHan commented on frontend/src/components/details/CounterPlayer.js
> +            <div className="total-container">
images-wrapper의 width를 100%로 수정해주셨지만, 부모 div의 class인 total-container의 width가 90%라서 여전히 가로스크롤의 범위가 100%에 미치지 않는 것 같네요.

2019-09-07 06:13 UTC, HyunSangHan commented on frontend/src/css/Main.scss
> +    width: 90%;
여기가 90%네요. images-wrapper보다 부모 div에는 images-wrapper의 목표 너비인 100%를 제한할 것이 없어야합니다. 지금은 total-contatiner라는 것으로 감싸버려서 문제가 있는 것입니다.

2019-09-08 03:36 UTC, HyunsangHan approved these changes
고생하셨습니다!ㅎㅎ

2019-09-08 03:37 UTC, merged